### ISSUE TITLE
When theme is active "Chrome" browser scrollbar is not working.

### ISSUE THREAD

**Issue by vivek-kumar-poddar** [saltnpixels/seasaltpress#7]
I think when your theme is activated Google Chrome scrollbar gets hidden.

**Comment by vivek-kumar-poddar** [comment]
The problem is arising due to:

line no 405, style.css;
line no 405, editor-style.css;
line no 392, _normalize_alignments_clearings.scss.

*::-webkit-scrollbar {
    display: none;
}

**Comment by saltnpixels** [comment]
Yeah I don't like scroll bars but I guess I can remove that...
really I don't like scroll bars inside a div because on ms windows it can ruin my designs.

I guess I can remove that if people would rather that not be included.

Thanks

**Comment by garrettw** [comment]
I can understand your design-motivated reasons, but to me removing the scrollbar creates a usability issue.

**Comment by saltnpixels** [comment]
Alright. I guess i can remove it and leave that up to users. Do you feel even divs within the page should have scrollbars? Like an overflowed div?

**Comment by garrettw** [comment]
I think users need to be able to tell somehow that it's scrollable, so that they don't just get annoyed by content looking cut off. Plus you have to consider users that need accessibility.

**Comment by saltnpixels** [comment]
Alright I'll remove it and let people put it back should they want to.
